/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDIBS7SPjcWNgesgxYjSY46g",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-08250bf547c11908f",
            securityGroupIds: [
                "sg-0f957131613dddb96",
                "sg-083ec72de129a1640"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-0e0abf0f542849cc7",
                    availabilityZone: "eu-central-1b"
                },
                {
                    subnetId: "subnet-04c8cf3296fa12b68",
                    availabilityZone: "eu-central-1a"
                },
                {
                    subnetId: "subnet-0ee52a9ee21cad965",
                    availabilityZone: "eu-central-1c"
                }
            ]
        }
    }
}).schema({
    "customer": a.model({
        id: a.id().required(),
        name: a.string().required(),
        email: a.string().required(),
        phone: a.string(),
        createdat: a.datetime(),
        updatedat: a.datetime()
    }).identifier([
        "id"
    ]),
    "opportunity": a.model({
        id: a.id().required(),
        name: a.string().required(),
        description: a.string(),
        stage: a.enum([
            "Closed_Lost",
            "Closed_Won",
            "Negotiation",
            "Proposal",
            "Qualification",
            "Prospecting"
        ]),
        amount: a.integer().required(),
        closedate: a.date(),
        accountid: a.string().required(),
        customerid: a.id().required(),
        createdat: a.datetime(),
        updatedat: a.datetime()
    }).identifier([
        "id"
    ])
});
